KeyError: 'anatomical-structure-schema' resolved. it was caused due to an attribute(subject_parcellation_term) being defined twice. Solution: defined it as a slot.